### ISSUE TITLE
Fault::exception does not work as factory alone, seems to actually throw exception

### ISSUE THREAD

**Issue by alextech** [omegad-biz/fault-manager#8] opened 2018-04-25 14:03 UTC
Here I am "converting"  exception from a different library to a custom exception so I know semantically what happened 
```
try {
   $worksheet = $spreadsheet->getSheet(5);
   } catch (\PhpOffice\PhpSpreadsheet\Exception $e) {
   throw Fault::exception(\ImporterException::class, 'Problem selecting sheet', 1002, $e);
}
```

This results in 
```
ImporterException : Problem selecting sheet
\vendor\omegad-biz\fault-manager\src\Fault.php:109
\src\Importer\src\Importer.php:123
\test\ImporterTest\ImporterTest.php:38
```

Exception is coming from within library, not my code.  Assuming this is a bug, because Fault::throw is supposed to have this behavior, while Fault::exception should act as a factory

**Comment by panosru** [comment] 2018-04-25 14:53
Les set some examples to check out what is the normal behaviour.

### Scenario 1:
*Throwing \Exception from within the function*

File: `test2.php`
```php
<?php
declare(strict_types=1);

function myAwesomeFunction() {
    throw new \Exception('exception message');
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

myAwesomeFunction();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/test2.php on line 5

Exception: exception message in /my/path/test2.php on line 5

Call Stack:
    0.0010     396624   1. {main}() /my/path/test-exception.php:0
    0.0180     396912   2. myAwesomeFunction() /my/path/test-exception.php:6
```
---
### Scenario 2:
*Return \Exception from the function and throw it in another place*

File: `test2.php`
```php
<?php
declare(strict_types=1);

function myAwesomeFunction() {
    return new \Exception('exception message');
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

throw myAwesomeFunction();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/test2.php on line 5

Exception: exception message in /my/path/test2.php on line 5

Call Stack:
    0.0098     396624   1. {main}() /my/path/test-exception.php:0
```
---
### Scenario 3:
*Return instance of \Exception from ReflectionClass (as this is the way Fault::exception works*

File: `test2.php`
```php
<?php
declare(strict_types=1);

function myAwesomeFunction() {
    return (new \ReflectionClass(\Exception::class))->newInstanceArgs(['exception message']);
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

throw myAwesomeFunction();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/test2.php on line 5

Exception: exception message in /my/path/test2.php on line 5

Call Stack:
    0.0011     396624   1. {main}() /my/path/test-exception.php:0
```
---
### Scenario 3
*Return Fault::exception() from myAwesomeFunction()*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

function myAwesomeFunction() {
    return Omega\FaultManager\Fault::exception(\Exception::class, 'exception message');
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

throw myAwesomeFunction();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109

Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109

Call Stack:
    0.0010     396624   1. {main}() /my/path/test-exception.php:0
```

Clearly, we don't get an expected behaviour here... I'm not yet sure what is wrong, that needs further investigation.

Thanks for reporting it!

**Comment by panosru** [comment] 2018-04-25 14:56
[Fault.php#L109](https://github.com/omegad-biz/fault-manager/blob/master/src/Fault.php#L109) does exactly what *Scenario 3* does... I'm not quite sure why the behaviour is not as expected.

**Comment by panosru** [comment] 2018-04-25 15:13
Testing with Class also results in the same behaviour...

### Scenario 5:
*Return \Exception from AwesomeClass::myAwesomeMethod()*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

class AwesomeClass
{
    public static function myAwesomeMethod(): \Throwable
    {
        return new \Exception('exception message');
    }
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

throw AwesomeClass::myAwesomeMethod();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/test2.php on line 10

Exception: exception message in /my/path/test2.php on line 10

Call Stack:
    0.0009     396632   1. {main}() /my/path/test-exception.php:0
```
---
### Scenario 6:
*Return Fault::exception() from AwesomeClass::myAwesomeMethod()*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

class AwesomeClass
{
    public static function myAwesomeMethod(): \Throwable
    {
        return \Omega\FaultManager\Fault::exception(\Exception::class, 'exception message');
    }
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

throw AwesomeClass::myAwesomeMethod();
```

Result:
```
Fatal error: Uncaught Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109

Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109

Call Stack:
    0.0009     396632   1. {main}() /my/path/test-exception.php:0
```

🤔 ❓

**Comment by panosru** [comment] 2018-04-25 15:15
Even if I change [Fault.php#L109](https://github.com/omegad-biz/fault-manager/blob/master/src/Fault.php#L109) to `return new $exceptionClass($message, $code, $previous);` for quick testing, I got exactly the same behaviour as in *Scenario 6* and *4*...

**Comment by panosru** [comment] 2018-04-25 18:44
Continuing with some more scenarios with exception output on browser:

### Scenario 7:
*Return \Exception from AwesomeClass::myAwesomeMethod()*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

class AwesomeClass
{
    public static function myAwesomeMethod(): \Throwable
    {
        return self::notSoAwesomeMethod();
    }

    private static function notSoAwesomeMethod(): \Throwable
    {
        return new \Exception('exception message', 1234);
    }
}
```

File: `test-exception.php`
```php
<?php
declare(strict_types=1);

require_once 'test2.php';

$exception = AwesomeClass::myAwesomeMethod();

\var_dump($exception);

throw $exception;
```

Result:
```
/my/path/test-exception.php:8:
object(Exception)[15]
  protected 'message' => string 'exception message' (length=17)
  private 'string' => string '' (length=0)
  protected 'code' => int 1234
  protected 'file' => string '/my/path/test2.php' (length=60)
  protected 'line' => int 15
  private 'trace' => 
    array (size=2)
      0 => 
        array (size=6)
          'file' => string '/my/path/test2.php' (length=60)
          'line' => int 10
          'function' => string 'notSoAwesomeMethod' (length=18)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
      1 => 
        array (size=6)
          'file' => string '/my/path/test-exception.php' (length=69)
          'line' => int 6
          'function' => string 'myAwesomeMethod' (length=15)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
  private 'previous' => null

( ! ) Fatal error: Uncaught Exception: exception message in /my/path/test2.php on line 15
( ! ) Exception: exception message in /my/path/test2.php on line 15
Call Stack
#	Time	Memory	Function	Location
1	0.0001	405200	{main}( )	.../test-exception.php:0
```
---
### Scenario 8:
*Return Fault::exception(\Exception::class, 'exception message', 1234)*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

class AwesomeClass
{
    public static function myAwesomeMethod(): \Throwable
    {
        return self::notSoAwesomeMethod();
    }

    private static function notSoAwesomeMethod(): \Throwable
    {
        return \Omega\FaultManager\Fault::exception(\Exception::class, 'exception message', 1234);
    }
}
```

File: `test-exception.php` is the same as in *Scenario 7*

Result:
```
/my/path/test-exception.php:8:
object(Exception)[17]
  protected 'message' => string 'exception message' (length=17)
  private 'string' => string '' (length=0)
  protected 'code' => int 1234
  protected 'file' => string '/my/path/vendor/omegad-biz/fault-manager/src/Fault.php' (length=96)
  protected 'line' => int 109
  private 'trace' => 
    array (size=4)
      0 => 
        array (size=6)
          'file' => string '/my/path/vendor/omegad-biz/fault-manager/src/Fault.php' (length=96)
          'line' => int 109
          'function' => string 'newInstanceArgs' (length=15)
          'class' => string 'ReflectionClass' (length=15)
          'type' => string '->' (length=2)
          'args' => 
            array (size=1)
              ...
      1 => 
        array (size=6)
          'file' => string '/my/path/test2.php' (length=60)
          'line' => int 16
          'function' => string 'exception' (length=9)
          'class' => string 'Omega\FaultManager\Fault' (length=24)
          'type' => string '::' (length=2)
          'args' => 
            array (size=3)
              ...
      2 => 
        array (size=6)
          'file' => string '/my/path/test2.php' (length=60)
          'line' => int 10
          'function' => string 'notSoAwesomeMethod' (length=18)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
      3 => 
        array (size=6)
          'file' => string '/my/path/test-exception.php' (length=69)
          'line' => int 6
          'function' => string 'myAwesomeMethod' (length=15)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
  private 'previous' => null


( ! ) Fatal error: Uncaught Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109
( ! ) Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109
Call Stack
#	Time	Memory	Function	Location
1	0.0001	405200	{main}( )	.../test-exception.php:0
```
---
### Scenario 9:
*Return Fault::exception(\Exception::class, 'exception message', 1234) but on [Fault.php#L109](https://github.com/omegad-biz/fault-manager/blob/master/src/Fault.php#L109) instead of `return (new \ReflectionClass($exceptionClass))->newInstanceArgs($params);` I set `return new $exceptionClass($message, $code, $previous);`*

File: `test2.php`
```php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

class AwesomeClass
{
    public static function myAwesomeMethod(): \Throwable
    {
        return self::notSoAwesomeMethod();
    }

    private static function notSoAwesomeMethod(): \Throwable
    {
        return \Omega\FaultManager\Fault::exception(\Exception::class, 'exception message', 1234);
    }
}
```

File: `test-exception.php` is the same as in *Scenario 7*

Result:
```
/my/path/test-exception.php:8:
object(Exception)[16]
  protected 'message' => string 'exception message' (length=17)
  private 'string' => string '' (length=0)
  protected 'code' => int 1234
  protected 'file' => string '/my/path/vendor/omegad-biz/fault-manager/src/Fault.php' (length=96)
  protected 'line' => int 109
  private 'trace' => 
    array (size=3)
      0 => 
        array (size=6)
          'file' => string '/my/path/test2.php' (length=60)
          'line' => int 16
          'function' => string 'exception' (length=9)
          'class' => string 'Omega\FaultManager\Fault' (length=24)
          'type' => string '::' (length=2)
          'args' => 
            array (size=3)
              ...
      1 => 
        array (size=6)
          'file' => string '/my/path/test2.php' (length=60)
          'line' => int 10
          'function' => string 'notSoAwesomeMethod' (length=18)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
      2 => 
        array (size=6)
          'file' => string '/my/path/test-exception.php' (length=69)
          'line' => int 6
          'function' => string 'myAwesomeMethod' (length=15)
          'class' => string 'AwesomeClass' (length=12)
          'type' => string '::' (length=2)
          'args' => 
            array (size=0)
              ...
  private 'previous' => null


( ! ) Fatal error: Uncaught Exception: exception message in /my/path/vendor/omegad-biz/fault-manager/src/Fault.php on line 109
( ! ) Exception: exception message in /my/path/aviant/vendor/omegad-biz/fault-manager/src/Fault.php on line 109
Call Stack
#	Time	Memory	Function	Location
1	0.0001	405200	{main}( )	.../test-exception.php:0

```

Seeing that stack trace, I'm thinking what possible solution can I provide in order to not keep scemantics in place and not alter the core functionality of exceptions. The way I see it currently is that the `return (new \ReflectionClass($exceptionClass))->newInstanceArgs($params);` from `Fault::exception()` should be removed, and use `return new $exceptionClass($message, $code, $previous);` instead.

That will keep the stack trace clean, so that solves a part of the issue

Then I could use something like that to alter the exception object (thankfully or not, nothing is truly immutable in PHP :P)

```php
$reflection = new \ReflectionObject($exception);

// Get trace and reverse it
$trace = $reflection->getProperty('trace');
$trace->setAccessible(true);
$last_trace = end($trace->getValue($exception));

// Set "file" and "line" properties
$file = $reflection->getProperty('file');
$file->setAccessible(true);
$file->setValue($exception, $last_trace['file']);

$line = $reflection->getProperty('line');
$line->setAccessible(true);
$line->setValue($exception, $last_trace['line']);
```

That I believe would solve the issue, what do you think?

I will run some tonight to test it.

**Comment by panosru** [comment] 2018-04-25 23:27
A much as don't particularly like to "mess" things with Reflection, it seems that in the current case there is no other solution.

This is how PHP works, many things in PHP disappoints me and that became one of them, but of course, many things make me happy as well.

From [PHP Manual](http://php.net/manual/en/throwable.getline.php): `Returns the line number where the thrown object was instantiated.` which means that it does not return the line where the exception is thrown. That usually is not a problem since usually we do `throw new \Exception...` but if you want to do things dynamically and pass exceptions as variables and throw them in another place, well that apparently is something that PHP doesn't like.

So having the following:
```php
<?php
try {
    $e = new \Exception('some message');
    // Do something here for whatever reason
    throw $e;
} catch(\Throwable $e) {
    echo "The exception was thrown on line: {$e->getLine()}";
}
```
would result in `The exception was thrown on line: 3` as can be shown [here](https://3v4l.org/C2YR1)

Also to my surprise, that was something [found back in 2011](https://bugs.php.net/bug.php?id=53882), and instead of proposing *fixing* that behaviour, a proposition was made to "fix" the documentation in order to reflect that behaviour! Even further, what surprises me the most is that the proposition was accepted! I even went further, [back in 2009](https://web.archive.org/web/20090608140729/http://php.net/manual/en/exception.getline.php) on the same page it was saying: `Returns line number where the exception was thrown.`.

If you ask me, I believe that the error message should report the line where the exception was thrown and now where it was instantiated. As for the information, I would like to have both when I catch my exception so I could know where it was thrown and where it was instantiated (for whatever reason).

From my point of view, that is something that needs to be reported to PHP team, as for the current library I will solve the issue with the help of reflectors as I cannot see any more suitable solution for now.

**Comment by panosru** [comment] 2018-04-26 00:00
@alextech I'm not closing it yet I would love it if you could provide some info on your side as well.

**Closed** 2018-04-26 13:48 UTC
Labels: bug

**Comment by alextech** [comment] 2018-04-26 14:44
Not seeing how that conversation can go well. One of those things, that probably a bunch of old legacy code depends on this, that no one will want to change.
One comment also says that is how java is doing it too. I checked, and indeed, that is how exceptions work there too. Now, just because something else does same thing does not make it "right", but overall it seems to be a general "standard" XD

So, since exception must be created at exact place of being thrown, I thought of a different method: to completely rely on autoloading http://php.net/manual/en/function.spl-autoload-register.php

instead of throw Fault::exception(),  do
```
throw CustomException::class
```

Of course at that point, CustomException does not exist anywhere in PSR-4 path, so PHP will run the autoloader function. This function will compile the class if its not there, make sure its loadable with `require`. Once loaded, new instance will be created at the `throw` line.

**Comment by panosru** [comment] 2018-04-26 16:32
Well in that case, of course, another option is to create manually the exceptions and just use `throw new CustomException();` :P
